/*
YASM (Yet Another Skill Management) API

This is an example of using OAuth2 Implicit Flow in a specification to describe security to your API.

API version: 1.88.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the TaskDescription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskDescription{}

// TaskDescription struct for TaskDescription
type TaskDescription struct {
	TaskDescription string `json:"taskDescription"`
	TaskType AvailabilityType `json:"taskType"`
}

// NewTaskDescription instantiates a new TaskDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskDescription(taskDescription string, taskType AvailabilityType) *TaskDescription {
	this := TaskDescription{}
	this.TaskDescription = taskDescription
	this.TaskType = taskType
	return &this
}

// NewTaskDescriptionWithDefaults instantiates a new TaskDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskDescriptionWithDefaults() *TaskDescription {
	this := TaskDescription{}
	return &this
}

// GetTaskDescription returns the TaskDescription field value
func (o *TaskDescription) GetTaskDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskDescription
}

// GetTaskDescriptionOk returns a tuple with the TaskDescription field value
// and a boolean to check if the value has been set.
func (o *TaskDescription) GetTaskDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskDescription, true
}

// SetTaskDescription sets field value
func (o *TaskDescription) SetTaskDescription(v string) {
	o.TaskDescription = v
}

// GetTaskType returns the TaskType field value
func (o *TaskDescription) GetTaskType() AvailabilityType {
	if o == nil {
		var ret AvailabilityType
		return ret
	}

	return o.TaskType
}

// GetTaskTypeOk returns a tuple with the TaskType field value
// and a boolean to check if the value has been set.
func (o *TaskDescription) GetTaskTypeOk() (*AvailabilityType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskType, true
}

// SetTaskType sets field value
func (o *TaskDescription) SetTaskType(v AvailabilityType) {
	o.TaskType = v
}

func (o TaskDescription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskDescription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["taskDescription"] = o.TaskDescription
	toSerialize["taskType"] = o.TaskType
	return toSerialize, nil
}

type NullableTaskDescription struct {
	value *TaskDescription
	isSet bool
}

func (v NullableTaskDescription) Get() *TaskDescription {
	return v.value
}

func (v *NullableTaskDescription) Set(val *TaskDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskDescription(val *TaskDescription) *NullableTaskDescription {
	return &NullableTaskDescription{value: val, isSet: true}
}

func (v NullableTaskDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


